
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF95rr2yPwHchwJJqMm8-qmoC_Np6_jZo',
    appId: '1:562708667564:web:8907cd08dbc1a3d4c2d309',
    messagingSenderId: '562708667564',
    projectId: 'esp32-mq135-9bdd0',
    authDomain: 'esp32-mq135-9bdd0.firebaseapp.com',
    databaseURL: 'https://esp32-mq135-9bdd0-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mq135-9bdd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALPgh0PCtdw-54T_qhsumS7LQIugMPQi4',
    appId: '1:562708667564:android:a228d4be370242f6c2d309',
    messagingSenderId: '562708667564',
    projectId: 'esp32-mq135-9bdd0',
    databaseURL: 'https://esp32-mq135-9bdd0-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mq135-9bdd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyCUrt599jbJ3Q3ihh8SsN6ZJamCL0HY',
    appId: '1:562708667564:ios:00bcd258226ea56ec2d309',
    messagingSenderId: '562708667564',
    projectId: 'esp32-mq135-9bdd0',
    databaseURL: 'https://esp32-mq135-9bdd0-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mq135-9bdd0.appspot.com',
    iosBundleId: 'com.example.trspecmr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwyCUrt599jbJ3Q3ihh8SsN6ZJamCL0HY',
    appId: '1:562708667564:ios:35609e57984ccb27c2d309',
    messagingSenderId: '562708667564',
    projectId: 'esp32-mq135-9bdd0',
    databaseURL: 'https://esp32-mq135-9bdd0-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-mq135-9bdd0.appspot.com',
    iosBundleId: 'com.example.trspecmr.RunnerTests',
  );
}
